print("Hello world")
print("Intformation and Network Engineering")
print("Anirach you will be a good Engineer")
print("I'm hungry")
print('He ask me "Who are you"')
print('/\\')
print("I'm good and \"I will do my best\"")